CREATE DATABASE  IF NOT EXISTS `ORO_DB` /*!40100 DEFAULT CHARACTER SET latin1 */;
USE `ORO_DB`;


--
-- Table structure for table `ORO_USERS`
--

DROP TABLE IF EXISTS `ORO_USERS`;

CREATE TABLE `ORO_USERS` (
  `UUID` varchar(250) NOT NULL,
  `USER_ID` varchar(100) NOT NULL,
  `ROLE_NAME` varchar(100) NOT NULL,
  `PROFILE_PIC` varchar(100) NOT NULL,
  `BIRTH_DATE` date DEFAULT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `USER_UUID_UNIQUE` (`UUID`)
) ;

