CREATE DATABASE  IF NOT EXISTS `ORO_DB` ;
USE `ORO_DB`;


DROP TABLE IF EXISTS `ORO_LOCATIONS`;

CREATE TABLE `ORO_LOCATIONS` (
  `UUID` varchar(250) NOT NULL,
  `ADDRESS_STREET` varchar(200) NOT NULL,
  `APT_NO` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `COUNTRY` varchar(45) NOT NULL,
  `ZIP` varchar(45) NOT NULL,
  `LATITUDE` double(10,8) NOT NULL,
  `LONGITUDE` double(11,8) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `LOCATION_UUID_UNIQUE` (`UUID`)
) ;

