CREATE DATABASE  IF NOT EXISTS `ORO_DB`;
USE `ORO_DB`;
--
-- Table structure for table `ORO_LOCATIONS`
--

DROP TABLE IF EXISTS `ORO_LOCATIONS`;
CREATE TABLE `ORO_LOCATIONS` (
  `UUID` varchar(250) NOT NULL,
  `ADDRESS_STREET` varchar(200) NOT NULL,
  `APT_NO` varchar(45) DEFAULT NULL,
  `CITY` varchar(45) NOT NULL,
  `STATE` varchar(45) NOT NULL,
  `COUNTRY` varchar(45) NOT NULL DEFAULT 'USA',
  `ZIP` varchar(45) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `LOCATION_UUID_UNIQUE` (`UUID`)
) ;