CREATE DATABASE  IF NOT EXISTS `ORO_DB` ;
USE `ORO_DB`;


--
-- Table structure for table `ORO_USER_LOCATIONS`
--

DROP TABLE IF EXISTS `ORO_USER_LOCATIONS`;

CREATE TABLE `ORO_USER_LOCATIONS` (
  `UUID` varchar(250) NOT NULL,
  `USER_UUID` varchar(250) NOT NULL,
  `LOCATION_UUID` varchar(250) NOT NULL,
  `IS_DEFAULT_LOCATION` tinyint(1) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`UUID`)
) ;


