CREATE DATABASE  IF NOT EXISTS `ORO_DB` ;
USE `ORO_DB`;

--
-- Table structure for table `ORO_CUISINE`
--

DROP TABLE IF EXISTS `ORO_CUISINE`;

CREATE TABLE `ORO_CUISINE` (
  `UUID` varchar(250) NOT NULL,
  `CUISINE_TYPE` varchar(45) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `UUID_UNIQUE` (`UUID`)
) ;

