CREATE DATABASE  IF NOT EXISTS `ORO_DB` ;
USE `ORO_DB`;


--
-- Table structure for table `ORO_RESTAURANTS`
--

DROP TABLE IF EXISTS `ORO_RESTAURANTS`;

CREATE TABLE `ORO_RESTAURANTS` (
  `UUID` varchar(250) NOT NULL,
  `REST_NAME` varchar(100) NOT NULL,
  `LOCATION_UUID` varchar(250) NOT NULL,
  `REST_ICON` varchar(100) NOT NULL,
  `REST_URL` varchar(100) DEFAULT NULL,
  `REST_EMAIL` varchar(45) NOT NULL,
  `REST_CONTACT` varchar(45) NOT NULL,
  `IS_ACTIVE` tinyint(1) NOT NULL,
  PRIMARY KEY (`UUID`),
  UNIQUE KEY `UUID_UNIQUE` (`UUID`)
) ;

